import { z } from 'zod';
import { blockCatalog } from './blockCatalog.js';
import { type BlockType, blockConfigSchemas, blockTypes, REVIEW_BLOCK_TYPES } from './blocks.js';
import type { SessionKind } from './state.js';

/** Where the generated reference lives in each skill, relative to the repo root, and the session kind it is for. */
export const BLOCKS_DOCS: readonly { path: string; kind: SessionKind }[] = [
    { path: 'skills/planroom/references/blocks.md', kind: 'plan' },
    { path: 'skills/planroom-ask/references/blocks.md', kind: 'ask' },
    { path: 'skills/planroom-review/references/blocks.md', kind: 'review' }
];

/** The block types a session kind takes: every type in a review, all but the review-only ones elsewhere. */
export function blockTypesFor(kind: SessionKind): BlockType[] {
    return kind === 'review' ? blockTypes : blockTypes.filter((type) => !REVIEW_BLOCK_TYPES.has(type));
}

/** How blocks are placed: in a write-up section, or on a review's slide. */
function placement(kind: SessionKind): string[] {
    if (kind !== 'review')
        return [
            'Every block is sent as `{ "type": "doc.block.upsert", "block": { "id", "type", "config", "caption"?, "refs"? } }` and placed',
            'in the write-up by a section that lists its id: `{ "type": "doc.section.upsert", "section": { "id", "title", "order", "blocks": [ids] } }`.',
            "Send a block before, or in the same batch as, the section that lists it. A block in a question's `context.blocks` or a `comment.reply`'s `blocks` has no `id`.",
            '',
            "- An entry in a section's `blocks` can be a list of two or three ids instead of one: those blocks sit side by side as columns, and",
            '  stack on a narrow screen. `"blocks": ["how-text", ["how-before", "how-after"], "how-seq"]` puts two diagrams next to each other.'
        ];
    return [
        'Every block is sent as `{ "type": "doc.block.upsert", "block": { "id", "type", "config", "caption"? } }` and placed on a slide',
        'that lists its id: `{ "type": "slide.upsert", "slide": { "id", "chapter", "order", "title", "blocks": [ids] } }`.',
        "Send a block before, or in the same batch as, the slide that lists it. A block in a `comment.reply`'s `blocks` has no `id`.",
        '',
        "- An entry in a slide's `blocks` can be a list of two or three ids instead of one: those blocks sit side by side as columns, and",
        '  stack on a narrow screen. `"blocks": ["how-text", ["how-before", "how-after"]]` puts two diagrams next to each other.',
        '- A block on a published slide is fixed for the round: re-sending it is refused.'
    ];
}

/** A block type's config schema as compact JSON Schema, without the `$schema` key. */
function schemaOf(type: (typeof blockTypes)[number]): string {
    const { $schema: _ignored, ...json } = z.toJSONSchema(blockConfigSchemas[type], {
        io: 'input',
        unrepresentable: 'any'
    }) as Record<string, unknown>;
    return JSON.stringify(json);
}

/**
 * The block catalog as the agent reads it: what each type is for, a config that
 * renders, and the exact config schema, all generated from the same zod schemas the
 * server validates with, so the reference cannot drift from the contract.
 */
export function renderBlocksDoc(kind: SessionKind): string {
    const types = blockTypesFor(kind);
    const lines = [
        '<!-- Generated by `pnpm generate:blocks-doc` from src/shared/blocks.ts and blockCatalog.ts. Do not edit by hand. -->',
        '',
        '# Planroom block catalog',
        '',
        ...placement(kind),
        ...(kind === 'review' ? [] : ['- `refs` are the question ids the block came from (`["Q-12"]`); the page links them.']),
        `- Text in any config is shown as text. Never send HTML: it is displayed literally${kind === 'review' ? ', except in an `html` block' : ''}.`,
        '- Diagrams take nodes and edges only; the page lays them out. Chart colours come from the page, never from you.',
        '- A config that fails its schema is still stored and shown as an error card, and `planroom_emit` lists it in `blockProblems`',
        "  with each field path. Fix it in place: re-send a write-up block with the same `id`, a question's context with `question.upsert`,",
        '  and a reply\'s blocks with `{ "type": "comment.edit", "messageId": "C-1.2", "blocks": [...] }`, the message id `blockProblems` names.',
        '',
        '## Contents',
        '',
        ...types.map((type) => `- [\`${type}\`](#${type.toLowerCase()}): ${blockCatalog[type].title}`),
        ''
    ];
    for (const type of types) {
        const entry = blockCatalog[type];
        lines.push(`## ${type}`, '', `**${entry.title}.** ${entry.use}`, '');
        if (entry.notes?.length) lines.push(...entry.notes.map((note) => `- ${note}`), '');
        lines.push(
            'Example config:',
            '',
            '```json',
            JSON.stringify(entry.example, null, 2),
            '```',
            '',
            'Config schema:',
            '',
            '```json',
            schemaOf(type),
            '```',
            ''
        );
    }
    return `${lines.join('\n').trimEnd()}\n`;
}
