import { z } from 'zod';
import { blockCatalog } from './blockCatalog.js';
import { blockConfigSchemas, blockTypes } from './blocks.js';

/** Where the generated reference lives, relative to the repo root. */
export const BLOCKS_DOC_PATH = '.agents/skills/planroom/references/blocks.md';

/** A block type's config schema as compact JSON Schema, without the `$schema` key. */
function schemaOf(type: (typeof blockTypes)[number]): string {
    const { $schema: _ignored, ...json } = z.toJSONSchema(blockConfigSchemas[type], {
        io: 'input',
        unrepresentable: 'any'
    }) as Record<string, unknown>;
    return JSON.stringify(json);
}

/**
 * The block catalog as the agent reads it: what each type is for, a config that
 * renders, and the exact config schema, all generated from the same zod schemas the
 * server validates with, so the reference cannot drift from the contract.
 */
export function renderBlocksDoc(): string {
    const lines = [
        '<!-- Generated by `pnpm -C tools/planroom generate:blocks-doc` from src/shared/blocks.ts and blockCatalog.ts. Do not edit by hand. -->',
        '<!-- prettier-ignore-start -->',
        '',
        '# Planroom block catalog',
        '',
        'Every block is sent as `{ "type": "doc.block.upsert", "block": { "id", "type", "config", "caption"?, "refs"? } }` and placed',
        'in the write-up by a section that lists its id: `{ "type": "doc.section.upsert", "section": { "id", "title", "order", "blocks": [ids] } }`.',
        "Send a block before, or in the same batch as, the section that lists it. A block in a question's `context.blocks` or a `comment.reply`'s `blocks` has no `id`.",
        '',
        "- An entry in a section's `blocks` can be a list of two or three ids instead of one: those blocks sit side by side as columns, and",
        '  stack on a narrow screen. `"blocks": ["how-text", ["how-before", "how-after"], "how-seq"]` puts two diagrams next to each other.',
        '- `refs` are the question ids the block came from (`["Q-12"]`); the page links them.',
        '- Text in any config is shown as text. Never send HTML: it is displayed literally.',
        '- Diagrams take nodes and edges only; the page lays them out. Chart colours come from the page, never from you.',
        '- A config that fails its schema is still stored and shown as an error card, and `planroom_emit` lists it in `blockProblems`',
        "  with each field path. Fix it in place: re-send a write-up block with the same `id`, a question's context with `question.upsert`,",
        '  and a reply\'s blocks with `{ "type": "comment.edit", "messageId": "C-1.2", "blocks": [...] }`, the message id `blockProblems` names.',
        '',
        '## Contents',
        '',
        ...blockTypes.map((type) => `- [\`${type}\`](#${type.toLowerCase()}): ${blockCatalog[type].title}`),
        ''
    ];
    for (const type of blockTypes) {
        const entry = blockCatalog[type];
        lines.push(`## ${type}`, '', `**${entry.title}.** ${entry.use}`, '');
        if (entry.notes?.length) lines.push(...entry.notes.map((note) => `- ${note}`), '');
        lines.push(
            'Example config:',
            '',
            '```json',
            JSON.stringify(entry.example, null, 2),
            '```',
            '',
            'Config schema:',
            '',
            '```json',
            schemaOf(type),
            '```',
            ''
        );
    }
    return `${lines.join('\n').trimEnd()}\n\n<!-- prettier-ignore-end -->\n`;
}
